name: Release mosdns docker

on:
  push:
    paths:
      - "Dockerfile"
      - ".github/workflows/release.yml"
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set build TAG as current time
        run: |
          # 使用 UTC 时间生成唯一 TAG，例如 20250813-1830
          BUILD_TAG=$(date -u +"%Y%m%d-%H%M")
          echo "BUILD_TAG=$BUILD_TAG" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          build-args: |
            TAG=${{ env.BUILD_TAG }}
            REPOSITORY=pmkol/mosdns-x
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mosdns-x-docker:latest
            ghcr.io/${{ github.repository_owner }}/mosdns-x-docker:${{ env.BUILD_TAG }}
